sudo: required

services:
  - docker

script:
  - docker build -t excel61/multi-client ./client
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push excel61/multi-client
